'use client';

import { Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface DownloadReportButtonProps {
    orders: any[];
    totals: any;
    driverName: string;
    range: string;
    generatedBy: string;
    userRole: string;
}

export default function DownloadReportButton({ orders, totals, driverName, range, generatedBy, userRole }: DownloadReportButtonProps) {

    const handleDownload = () => {
        const doc = new jsPDF();

        // Brand Header (Orange-600: #ea580c -> 234, 88, 12)
        doc.setFontSize(22);
        doc.setTextColor(234, 88, 12);
        doc.setFont('helvetica', 'bold');
        doc.text('SAPTHAGIRI FOODS', 105, 20, { align: 'center' });

        // Subheader
        doc.setTextColor(60, 60, 60);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'normal');
        doc.text('Driver Performance Report', 105, 30, { align: 'center' });

        // Metadata Box
        doc.setDrawColor(200, 200, 200);
        doc.line(14, 35, 196, 35); // Horizontal line

        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);

        doc.text(`Driver Name:`, 14, 45);
        doc.setFont('helvetica', 'bold');
        doc.text(driverName, 40, 45);

        doc.setFont('helvetica', 'normal');
        doc.text(`Report Range:`, 14, 52);
        doc.setFont('helvetica', 'bold');
        doc.text(range.toUpperCase(), 40, 52);

        doc.setFont('helvetica', 'normal');
        doc.text(`Generated By:`, 120, 45);
        doc.text(`${generatedBy} (${userRole})`, 150, 45);

        doc.text(`Date Generated:`, 120, 52);
        doc.text(new Date().toLocaleString(), 150, 52);

        // Summary Cards Section (Drawn manually)
        const startY = 60;
        const boxWidth = 40;
        const boxHeight = 25;
        const gap = 6;

        // Helper to draw stat box
        const drawStatBox = (x: number, label: string, value: string, color: [number, number, number]) => {
            doc.setFillColor(250, 250, 250);
            doc.setDrawColor(220, 220, 220);
            doc.roundedRect(x, startY, boxWidth, boxHeight, 2, 2, 'FD');

            doc.setFontSize(8);
            doc.setTextColor(100, 100, 100);
            doc.text(label, x + 5, startY + 8);

            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...color);
            doc.text(value, x + 5, startY + 18);
        };

        drawStatBox(14, 'Total Deliveries', totals.totalDeliveries.toString(), [50, 50, 50]);
        drawStatBox(14 + boxWidth + gap, 'Revenue', `Rs. ${totals.totalRevenue}`, [0, 0, 0]);
        drawStatBox(14 + (boxWidth + gap) * 2, 'Cash Collected', `Rs. ${totals.totalCash}`, [147, 51, 234]); // Purple
        drawStatBox(14 + (boxWidth + gap) * 3, 'UPI Collected', `Rs. ${totals.totalUpi}`, [37, 99, 235]); // Blue

        // Data Table
        const tableBody = orders.map((o) => {
            let payMode = o.paymentMethod?.toUpperCase() || 'N/A';
            if (o.paymentMethod === 'split') {
                payMode = `SPLIT\nC:${o.cashPaid} U:${o.upiPaid}`;
            }
            if (o.type === 'collection') {
                payMode += '\n(COLLECTION)';
            }

            const collectedBy = o.collectedBy === 'OWNER' ? 'OWNER' : (o.collectorName || 'DRIVER');

            return [
                new Date(o.date).toLocaleDateString() + `\n${new Date(o.date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`,
                o.storeName,
                payMode,
                `Rs. ${o.totalAmount}`,
                `Rs. ${o.paidAmount}`,
                `Rs. ${(o.totalAmount || 0) - (o.paidAmount || 0)}`,
                collectedBy
            ];
        });

        autoTable(doc, {
            startY: startY + boxHeight + 10,
            head: [['Date/Time', 'Store', 'Pay Mode', 'Total', 'Paid', 'Balance', 'Collected By']],
            body: tableBody,
            theme: 'grid',
            headStyles: {
                fillColor: [234, 88, 12], // Orange-600
                textColor: 255,
                fontStyle: 'bold',
                halign: 'center'
            },
            columnStyles: {
                0: { cellWidth: 30 },
                1: { cellWidth: 'auto' },
                3: { halign: 'right' },
                4: { halign: 'right' },
                5: { halign: 'right', fontStyle: 'bold', textColor: [220, 38, 38] }, // Red for Balance
                6: { halign: 'center' }
            },
            alternateRowStyles: { fillColor: [255, 247, 237] }, // Very light orange/gray
            styles: {
                fontSize: 9,
                cellPadding: 3,
                valign: 'middle'
            }
        });

        // Final Totals Footer
        const finalY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text('*** End of Computer Generated Report ***', 105, finalY, { align: 'center' });
        doc.text('Sapthagiri Foods - Confidential', 105, finalY + 5, { align: 'center' });

        doc.save(`Driver_Report_${driverName}_${range}.pdf`);
    };

    return (
        <button
            onClick={handleDownload}
            className="flex items-center gap-2 bg-orange-600 text-white px-4 py-2 rounded-xl font-bold shadow-lg shadow-orange-200 hover:bg-orange-700 hover:shadow-xl transition-all active:scale-95"
        >
            <Download className="w-4 h-4" />
            Download PDF
        </button>
    );
}
