'use client';

import { Download, Share2 } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportActionsCellProps {
    order: any;
    driverName: string; // This might be the driver OF the order
    generatedBy: string;
    userRole: string;
}

export default function ReportActionsCell({ order, driverName, generatedBy, userRole }: ReportActionsCellProps) {

    const handleDownloadPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(22, 163, 74); // Green-600 to match branding
        doc.text('SAPTHAGIRI FOODS', 105, 15, { align: 'center' });

        doc.setTextColor(0, 0, 0); // Reset color
        doc.setFontSize(10);
        doc.text('Hassan | Phone: 9611006622', 105, 23, { align: 'center' });
        doc.text(`Generated By: ${generatedBy} (${userRole})`, 105, 28, { align: 'center' });


        // Bill Info
        doc.setFontSize(12);
        const title = order.type === 'collection' ? 'PAYMENT RECEIPT' : 'INVOICE';
        doc.text(`${title}: #${order.id.slice(0, 8).toUpperCase()}`, 14, 35);
        doc.text(`Date: ${new Date(order.date).toLocaleDateString()}`, 14, 42);
        doc.text(`Store: ${order.storeName || 'N/A'}`, 14, 49);
        if (order.storeAddress) {
            doc.text(`Address: ${order.storeAddress}`, 14, 56);
        }

        let startY = 65;

        // Table (Only for Delivery)
        if (order.type !== 'collection') {
            const tableBody = order.items.map((item: any) => [
                item.itemName,
                item.quantity,
                `Rs. ${item.price}`,
                `Rs. ${item.quantity * item.price}`
            ]);

            autoTable(doc, {
                startY: 65,
                head: [['Item', 'Qty', 'Price', 'Total']],
                body: tableBody,
                theme: 'grid',
                headStyles: { fillColor: [41, 128, 185] },
            });
            startY = (doc as any).lastAutoTable.finalY + 10;
        } else {
            doc.setFontSize(10);
            doc.text('(Balance Payment - No Items Delivered)', 14, 60);
            startY = 70;
        }

        const finalY = startY;

        // Totals
        // Totals
        if (order.type !== 'collection') {
            doc.text(`Total Amount: Rs. ${order.totalAmount}`, 140, finalY);
        }
        let paymentInfo = `Paid: Rs. ${order.paidAmount}`;
        if (order.paymentMethod === 'split') {
            paymentInfo += ` (Cash: ${order.cashPaid}, UPI: ${order.upiPaid})`;
        } else {
            paymentInfo += ` (${order.paymentMethod?.toUpperCase()})`;
        }
        doc.text(paymentInfo, 140, finalY + (order.type !== 'collection' ? 7 : 0));

        // Collector Info
        if (order.collectorName) {
            doc.setFontSize(10);
            doc.text(`Collected By: ${order.collectedBy === 'OWNER' ? 'Owner' : order.collectorName}`, 14, finalY + 20);
        }

        // Footer
        doc.setFontSize(8);
        doc.text('Thank you for your business!', 105, 280, { align: 'center' });

        doc.save(`Invoice_${order.storeName}_${new Date(order.date).toISOString().split('T')[0]}.pdf`);
    };

    const handleWhatsApp = () => {
        // Construct message
        let message = `*INVOICE: ${order.storeName}*\n`;
        message += `Date: ${new Date(order.date).toLocaleDateString()}\n`;
        message += `------------------\n`;
        order.items.forEach((item: any) => {
            message += `${item.itemName} x ${item.quantity} = Rs.${item.quantity * item.price}\n`;
        });
        message += `------------------\n`;
        message += `*Total: Rs.${order.totalAmount}*\n`;
        if (order.paymentMethod === 'split') {
            message += `Paid: Rs.${order.paidAmount} (Cash: ${order.cashPaid}, UPI: ${order.upiPaid})\n`;
        } else {
            message += `Paid: Rs.${order.paidAmount} (${order.paymentMethod?.toUpperCase()})\n`;
        }
        message += `*Balance: Rs.${(order.totalAmount || 0) - (order.paidAmount || 0)}*\n`;

        const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
        window.open(url, '_blank');
    };

    return (
        <div className="flex gap-2 justify-end">
            <button
                onClick={handleDownloadPDF}
                className="p-2 text-blue-600 hover:bg-blue-50 rounded-full"
                title="Download Invoice PDF"
            >
                <Download className="w-4 h-4" />
            </button>
            <button
                onClick={handleWhatsApp}
                className="p-2 text-green-600 hover:bg-green-50 rounded-full"
                title="Share on WhatsApp"
            >
                <Share2 className="w-4 h-4" />
            </button>
        </div>
    );
}
